"""Add description to llm_configs

Revision ID: 62f08510c1a8
Revises: 242dbd3d98e0
Create Date: 2025-05-22 11:44:53.692791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f08510c1a8'
down_revision: Union[str, None] = '242dbd3d98e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'description')
    # ### end Alembic commands ###
