"""Add llama.cpp config fields

Revision ID: 645d6839f6a7
Revises: 1648bd84682a
Create Date: 2025-05-16 13:52:26.626757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '645d6839f6a7'
down_revision: Union[str, None] = '1648bd84682a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('checkpoints_thread_id_idx', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index('checkpoint_blobs_thread_id_idx', table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_table('checkpoint_migrations')
    op.drop_index('checkpoint_writes_thread_id_idx', table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.add_column('llm_models', sa.Column('chat_format', sa.String(), nullable=True))
    op.add_column('llm_models', sa.Column('n_ctx', sa.Integer(), nullable=True))
    op.add_column('llm_models', sa.Column('numa', sa.Integer(), nullable=True))
    op.add_column('llm_models', sa.Column('rope_scaling_type', sa.Integer(), nullable=True))
    op.add_column('llm_models', sa.Column('f16_kv', sa.Boolean(), nullable=True))
    op.add_column('llm_models', sa.Column('use_mlock', sa.Boolean(), nullable=True))
    op.add_column('llm_models', sa.Column('use_mmap', sa.Boolean(), nullable=True))
    op.add_column('llm_models', sa.Column('low_vram', sa.Boolean(), nullable=True))
    op.add_column('llm_models', sa.Column('offload_kqv', sa.Boolean(), nullable=True))
    op.add_column('llm_models', sa.Column('embedding', sa.Boolean(), nullable=True))
    op.add_column('llm_models', sa.Column('logits_all', sa.Boolean(), nullable=True))
    op.add_column('llm_models', sa.Column('verbose', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_models', 'verbose')
    op.drop_column('llm_models', 'logits_all')
    op.drop_column('llm_models', 'embedding')
    op.drop_column('llm_models', 'offload_kqv')
    op.drop_column('llm_models', 'low_vram')
    op.drop_column('llm_models', 'use_mmap')
    op.drop_column('llm_models', 'use_mlock')
    op.drop_column('llm_models', 'f16_kv')
    op.drop_column('llm_models', 'rope_scaling_type')
    op.drop_column('llm_models', 'numa')
    op.drop_column('llm_models', 'n_ctx')
    op.drop_column('llm_models', 'chat_format')
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name='checkpoint_writes_pkey')
    )
    op.create_index('checkpoint_writes_thread_id_idx', 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name='checkpoint_migrations_pkey')
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name='checkpoint_blobs_pkey')
    )
    op.create_index('checkpoint_blobs_thread_id_idx', 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name='checkpoints_pkey')
    )
    op.create_index('checkpoints_thread_id_idx', 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###
