"""baseline schema for ProjectMind

Revision ID: b119f2bef33d
Revises: c950264213ad
Create Date: 2025-05-16 01:33:51.813112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b119f2bef33d'
down_revision: Union[str, None] = 'c950264213ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agents_name_key', 'agents', type_='unique')
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_index(op.f('ix_agents_type'), 'agents', ['type'], unique=False)
    op.drop_column('agents', 'prompt')
    op.create_index(op.f('ix_prompts_agent_name'), 'prompts', ['agent_name'], unique=False)
    op.create_index('ix_prompts_agent_task', 'prompts', ['agent_name', 'task_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_prompts_created_at'), 'prompts', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompts_is_active'), 'prompts', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompts_task_type'), 'prompts', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_prompts_task_type'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_is_active'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_created_at'), table_name='prompts')
    op.drop_index('ix_prompts_agent_task', table_name='prompts')
    op.drop_index(op.f('ix_prompts_agent_name'), table_name='prompts')
    op.add_column('agents', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agents_type'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.create_unique_constraint('agents_name_key', 'agents', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
