"""add memories table with indexes

Revision ID: d51117ccf416
Revises: 9a2b7ba07416
Create Date: 2025-05-16 02:49:09.192274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51117ccf416'
down_revision: Union[str, None] = '9a2b7ba07416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_active_prompt', table_name='prompts', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_active_prompt', 'prompts', ['agent_name', 'task_type'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
