"""create planner_runs table

Revision ID: f74eac504b8c
Revises: 5a56d2f80010
Create Date: 2025-05-15 23:53:52.248615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74eac504b8c'
down_revision: Union[str, None] = '5a56d2f80010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('output_response', sa.Text(), nullable=False),
    sa.Column('task_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planner_runs')
    # ### end Alembic commands ###
